CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'heroescodefirst') THEN
        CREATE SCHEMA heroescodefirst;
    END IF;
END $EF$;

CREATE TABLE heroescodefirst."Personajes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(50) NOT NULL,
    "Nivel" integer NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Gremio" text,
    "Rasgos" jsonb,
    CONSTRAINT "PK_Personajes" PRIMARY KEY ("Id")
);

CREATE TABLE heroescodefirst."Arqueros" (
    "Id" integer NOT NULL,
    "Precision" double precision NOT NULL,
    "TieneMascota" boolean NOT NULL,
    CONSTRAINT "PK_Arqueros" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Arqueros_Personajes_Id" FOREIGN KEY ("Id") REFERENCES heroescodefirst."Personajes" ("Id") ON DELETE CASCADE
);

CREATE TABLE heroescodefirst."Clerigos" (
    "Id" integer NOT NULL,
    "Deidad" text NOT NULL,
    "PuntosSanacion" integer NOT NULL,
    CONSTRAINT "PK_Clerigos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Clerigos_Personajes_Id" FOREIGN KEY ("Id") REFERENCES heroescodefirst."Personajes" ("Id") ON DELETE CASCADE
);

CREATE TABLE heroescodefirst."Guerreros" (
    "Id" integer NOT NULL,
    "ArmaPrincipal" text NOT NULL,
    "Furia" integer NOT NULL,
    CONSTRAINT "PK_Guerreros" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Guerreros_Personajes_Id" FOREIGN KEY ("Id") REFERENCES heroescodefirst."Personajes" ("Id") ON DELETE CASCADE
);

CREATE TABLE heroescodefirst."Magos" (
    "Id" integer NOT NULL,
    "Mana" integer NOT NULL,
    "ElementoPrincipal" text NOT NULL,
    CONSTRAINT "PK_Magos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Magos_Personajes_Id" FOREIGN KEY ("Id") REFERENCES heroescodefirst."Personajes" ("Id") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260210132916_InitialCreate', '9.0.9');

COMMIT;

